import "@solidstarters/solid-core-ui";
import "@solidstarters/solid-core-ui";
import "@solidstarters/solid-core-ui"
import "primeicons/primeicons.css";
import "primeflex/primeflex.css";
import { Inter } from "next/font/google";
import { GlobalProvider } from "./GlobalProvider";
import { PrimeReactProvider } from "primereact/api";
import { LayoutProvider } from "@solidstarters/solid-core-ui";
import { SolidThemeProvider } from "@solidstarters/solid-core-ui";

const inter = Inter({
  subsets: ["latin"],
  weight: ['400', '700'], // Define weights, e.g., '400', '500', '700'
  variable: '--font-inter',
});

// Fetch a list of entities dynamically 
async function fetchEntities() {
  const url = `${process.env.NEXT_PUBLIC_BACKEND_API_URL}/api/model-metadata/public`;

  const response = await fetch(url, { cache: 'no-store' });
  const data = await response.json(); // Assume this returns an array of entity names
  const entities = data.data.records.map((r: any) => r.singularName);

  return entities
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const solidEntities = await fetchEntities();

  return (
    <html lang="en" suppressHydrationWarning>
      {/* <Head /> */}
      <head>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link id="theme-css" href={`/themes/solid-light-purple/theme.css`} rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Sharp" rel="stylesheet" />
      </head>
      <body>
        <GlobalProvider entities={solidEntities}>
          <PrimeReactProvider>
            <LayoutProvider>
            <SolidThemeProvider />
              {children}
            </LayoutProvider>
          </PrimeReactProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
